### ISSUE TITLE
Stale Repo

### ISSUE THREAD

**Issue by Mitchell-Str** [ruankie/f1-udp-telemetry#1]
This repo is stale; no recent pushes.

**Comment by ruankie** [comment]
@Mitchell-Str thank you for blessing this repo with your eagle eyes. Rest assured that swift action will be taken to rectify this situation.
Please refer to [this branch](https://github.com/ruankie/f1-udp-telemetry/tree/fix/stale-repo) to keep track of the action. A PR will soon be opened to address this issue.
